AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          # Replace <bucket> with your bucket name
          Parameters:
            Location: s3://aws-codestar-us-west-2-443954526038-lambdatest-app/swagger2.yaml
  GetHelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.get
      Runtime: nodejs4.3
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetEvent:
          Type: Api
          RestApiId: !Ref ApiGatewayApi
          Properties:
            Path: /test
            Method: get
        PostEvent:
          Type: Api
          RestApiId: !Ref ApiGatewayApi
          Properties:
            Path: /test
            Method: post
  GetHelloWorldTwo:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.get2
      Runtime: nodejs4.3
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetEvent:
          Type: Api
          RestApiId: !Ref ApiGatewayApi
          Properties:
            Path: /test2/
            Method: get
        PostEvent:
          Type: Api
          RestApiId: !Ref ApiGatewayApi
          Properties:
            Path: /test2/
            Method: post
  # Current workaround needed if you want to use the APIGW Console Test button
  # See https://github.com/awslabs/serverless-application-model/issues/59#issuecomment-348709355
  ConfigLambdaPermission:
    Type: "AWS::Lambda::Permission"
    DependsOn:
    - GetHelloWorld
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
      - !Ref GetHelloWorld
      Principal: apigateway.amazonaws.com